github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: Fetch dependencies
    init: |
      npm install -g npm
      npm install
vscode:
  extensions:
    - github.vscode-pull-request-github
    - octref.vetur
