github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: Fetch dependencies
    init: |
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt-get update
      sudo apt -y install ./google-chrome-stable_current_amd64.deb
      rm ./google-chrome-stable_current_amd64.deb
      npm install -g npm@8.1.4
      npm install
vscode:
  extensions:
    - github.vscode-pull-request-github
    - octref.vetur
