name: Main
on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: build
      run: npm run build_github_pages
 